/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as SnapshotsSelectionRouteImport } from './routes/snapshots-selection'
import { Route as TableRouteRouteImport } from './routes/table/route'
import { Route as TableIndexRouteImport } from './routes/table/index'
import { Route as TableFiletreeRouteImport } from './routes/table/filetree'
import { Route as TableGraphRouteImport } from './routes/table/graph'
import { Route as TableMetadataRouteImport } from './routes/table/metadata'
import { Route as TableTimelineRouteImport } from './routes/table/timeline'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const SnapshotsSelectionRoute = SnapshotsSelectionRouteImport.update({
  id: '/snapshots-selection',
  path: '/snapshots-selection',
  getParentRoute: () => rootRouteImport,
} as any)
const TableRouteRoute = TableRouteRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => rootRouteImport,
} as any)
const TableIndexRoute = TableIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TableRouteRoute,
} as any)
const TableFiletreeRoute = TableFiletreeRouteImport.update({
  id: '/filetree',
  path: '/filetree',
  getParentRoute: () => TableRouteRoute,
} as any)
const TableGraphRoute = TableGraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => TableRouteRoute,
} as any)
const TableMetadataRoute = TableMetadataRouteImport.update({
  id: '/metadata',
  path: '/metadata',
  getParentRoute: () => TableRouteRoute,
} as any)
const TableTimelineRoute = TableTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => TableRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/table': typeof TableRouteRouteWithChildren
  '/docs': typeof DocsRoute
  '/snapshots-selection': typeof SnapshotsSelectionRoute
  '/table/filetree': typeof TableFiletreeRoute
  '/table/graph': typeof TableGraphRoute
  '/table/metadata': typeof TableMetadataRoute
  '/table/timeline': typeof TableTimelineRoute
  '/table/': typeof TableIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/snapshots-selection': typeof SnapshotsSelectionRoute
  '/table/filetree': typeof TableFiletreeRoute
  '/table/graph': typeof TableGraphRoute
  '/table/metadata': typeof TableMetadataRoute
  '/table/timeline': typeof TableTimelineRoute
  '/table': typeof TableIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/table': typeof TableRouteRouteWithChildren
  '/docs': typeof DocsRoute
  '/snapshots-selection': typeof SnapshotsSelectionRoute
  '/table/filetree': typeof TableFiletreeRoute
  '/table/graph': typeof TableGraphRoute
  '/table/metadata': typeof TableMetadataRoute
  '/table/timeline': typeof TableTimelineRoute
  '/table/': typeof TableIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/table'
    | '/docs'
    | '/snapshots-selection'
    | '/table/filetree'
    | '/table/graph'
    | '/table/metadata'
    | '/table/timeline'
    | '/table/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/snapshots-selection'
    | '/table/filetree'
    | '/table/graph'
    | '/table/metadata'
    | '/table/timeline'
    | '/table'
  id:
    | '__root__'
    | '/'
    | '/table'
    | '/docs'
    | '/snapshots-selection'
    | '/table/filetree'
    | '/table/graph'
    | '/table/metadata'
    | '/table/timeline'
    | '/table/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TableRouteRoute: typeof TableRouteRouteWithChildren
  DocsRoute: typeof DocsRoute
  SnapshotsSelectionRoute: typeof SnapshotsSelectionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snapshots-selection': {
      id: '/snapshots-selection'
      path: '/snapshots-selection'
      fullPath: '/snapshots-selection'
      preLoaderRoute: typeof SnapshotsSelectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table': {
      id: '/table'
      path: '/table'
      fullPath: '/table'
      preLoaderRoute: typeof TableRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table/': {
      id: '/table/'
      path: '/'
      fullPath: '/table/'
      preLoaderRoute: typeof TableIndexRouteImport
      parentRoute: typeof TableRouteRoute
    }
    '/table/filetree': {
      id: '/table/filetree'
      path: '/filetree'
      fullPath: '/table/filetree'
      preLoaderRoute: typeof TableFiletreeRouteImport
      parentRoute: typeof TableRouteRoute
    }
    '/table/graph': {
      id: '/table/graph'
      path: '/graph'
      fullPath: '/table/graph'
      preLoaderRoute: typeof TableGraphRouteImport
      parentRoute: typeof TableRouteRoute
    }
    '/table/metadata': {
      id: '/table/metadata'
      path: '/metadata'
      fullPath: '/table/metadata'
      preLoaderRoute: typeof TableMetadataRouteImport
      parentRoute: typeof TableRouteRoute
    }
    '/table/timeline': {
      id: '/table/timeline'
      path: '/timeline'
      fullPath: '/table/timeline'
      preLoaderRoute: typeof TableTimelineRouteImport
      parentRoute: typeof TableRouteRoute
    }
  }
}

interface TableRouteRouteChildren {
  TableFiletreeRoute: typeof TableFiletreeRoute
  TableGraphRoute: typeof TableGraphRoute
  TableMetadataRoute: typeof TableMetadataRoute
  TableTimelineRoute: typeof TableTimelineRoute
  TableIndexRoute: typeof TableIndexRoute
}

const TableRouteRouteChildren: TableRouteRouteChildren = {
  TableFiletreeRoute: TableFiletreeRoute,
  TableGraphRoute: TableGraphRoute,
  TableMetadataRoute: TableMetadataRoute,
  TableTimelineRoute: TableTimelineRoute,
  TableIndexRoute: TableIndexRoute,
}

const TableRouteRouteWithChildren = TableRouteRoute._addFileChildren(
  TableRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TableRouteRoute: TableRouteRouteWithChildren,
  DocsRoute: DocsRoute,
  SnapshotsSelectionRoute: SnapshotsSelectionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
