/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellIndexRouteImport } from './routes/_shell/index'
import { Route as ShellDocsRouteImport } from './routes/_shell/docs'
import { Route as ShellSnapshotsSelectionRouteImport } from './routes/_shell/snapshots-selection'
import { Route as ShellTableRouteRouteImport } from './routes/_shell/table/route'
import { Route as ShellTableIndexRouteImport } from './routes/_shell/table/index'
import { Route as ShellTableFiletreeRouteImport } from './routes/_shell/table/filetree'
import { Route as ShellTableGraphRouteImport } from './routes/_shell/table/graph'
import { Route as ShellTableMetadataRouteImport } from './routes/_shell/table/metadata'
import { Route as ShellTableTimelineRouteImport } from './routes/_shell/table/timeline'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDocsRoute = ShellDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSnapshotsSelectionRoute = ShellSnapshotsSelectionRouteImport.update({
  id: '/snapshots-selection',
  path: '/snapshots-selection',
  getParentRoute: () => ShellRoute,
} as any)
const ShellTableRouteRoute = ShellTableRouteRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => ShellRoute,
} as any)
const ShellTableIndexRoute = ShellTableIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellTableRouteRoute,
} as any)
const ShellTableFiletreeRoute = ShellTableFiletreeRouteImport.update({
  id: '/filetree',
  path: '/filetree',
  getParentRoute: () => ShellTableRouteRoute,
} as any)
const ShellTableGraphRoute = ShellTableGraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => ShellTableRouteRoute,
} as any)
const ShellTableMetadataRoute = ShellTableMetadataRouteImport.update({
  id: '/metadata',
  path: '/metadata',
  getParentRoute: () => ShellTableRouteRoute,
} as any)
const ShellTableTimelineRoute = ShellTableTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => ShellTableRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/table': typeof ShellTableRouteRouteWithChildren
  '/docs': typeof ShellDocsRoute
  '/snapshots-selection': typeof ShellSnapshotsSelectionRoute
  '/table/filetree': typeof ShellTableFiletreeRoute
  '/table/graph': typeof ShellTableGraphRoute
  '/table/metadata': typeof ShellTableMetadataRoute
  '/table/timeline': typeof ShellTableTimelineRoute
  '/table/': typeof ShellTableIndexRoute
}
export interface FileRoutesByTo {
  '/docs': typeof ShellDocsRoute
  '/snapshots-selection': typeof ShellSnapshotsSelectionRoute
  '/': typeof ShellIndexRoute
  '/table/filetree': typeof ShellTableFiletreeRoute
  '/table/graph': typeof ShellTableGraphRoute
  '/table/metadata': typeof ShellTableMetadataRoute
  '/table/timeline': typeof ShellTableTimelineRoute
  '/table': typeof ShellTableIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/table': typeof ShellTableRouteRouteWithChildren
  '/_shell/docs': typeof ShellDocsRoute
  '/_shell/snapshots-selection': typeof ShellSnapshotsSelectionRoute
  '/_shell/': typeof ShellIndexRoute
  '/_shell/table/filetree': typeof ShellTableFiletreeRoute
  '/_shell/table/graph': typeof ShellTableGraphRoute
  '/_shell/table/metadata': typeof ShellTableMetadataRoute
  '/_shell/table/timeline': typeof ShellTableTimelineRoute
  '/_shell/table/': typeof ShellTableIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/table'
    | '/docs'
    | '/snapshots-selection'
    | '/table/filetree'
    | '/table/graph'
    | '/table/metadata'
    | '/table/timeline'
    | '/table/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/docs'
    | '/snapshots-selection'
    | '/'
    | '/table/filetree'
    | '/table/graph'
    | '/table/metadata'
    | '/table/timeline'
    | '/table'
  id:
    | '__root__'
    | '/_shell'
    | '/_shell/table'
    | '/_shell/docs'
    | '/_shell/snapshots-selection'
    | '/_shell/'
    | '/_shell/table/filetree'
    | '/_shell/table/graph'
    | '/_shell/table/metadata'
    | '/_shell/table/timeline'
    | '/_shell/table/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/docs': {
      id: '/_shell/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof ShellDocsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/snapshots-selection': {
      id: '/_shell/snapshots-selection'
      path: '/snapshots-selection'
      fullPath: '/snapshots-selection'
      preLoaderRoute: typeof ShellSnapshotsSelectionRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/table': {
      id: '/_shell/table'
      path: '/table'
      fullPath: '/table'
      preLoaderRoute: typeof ShellTableRouteRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/table/': {
      id: '/_shell/table/'
      path: '/'
      fullPath: '/table/'
      preLoaderRoute: typeof ShellTableIndexRouteImport
      parentRoute: typeof ShellTableRouteRoute
    }
    '/_shell/table/filetree': {
      id: '/_shell/table/filetree'
      path: '/filetree'
      fullPath: '/table/filetree'
      preLoaderRoute: typeof ShellTableFiletreeRouteImport
      parentRoute: typeof ShellTableRouteRoute
    }
    '/_shell/table/graph': {
      id: '/_shell/table/graph'
      path: '/graph'
      fullPath: '/table/graph'
      preLoaderRoute: typeof ShellTableGraphRouteImport
      parentRoute: typeof ShellTableRouteRoute
    }
    '/_shell/table/metadata': {
      id: '/_shell/table/metadata'
      path: '/metadata'
      fullPath: '/table/metadata'
      preLoaderRoute: typeof ShellTableMetadataRouteImport
      parentRoute: typeof ShellTableRouteRoute
    }
    '/_shell/table/timeline': {
      id: '/_shell/table/timeline'
      path: '/timeline'
      fullPath: '/table/timeline'
      preLoaderRoute: typeof ShellTableTimelineRouteImport
      parentRoute: typeof ShellTableRouteRoute
    }
  }
}

interface ShellTableRouteRouteChildren {
  ShellTableFiletreeRoute: typeof ShellTableFiletreeRoute
  ShellTableGraphRoute: typeof ShellTableGraphRoute
  ShellTableMetadataRoute: typeof ShellTableMetadataRoute
  ShellTableTimelineRoute: typeof ShellTableTimelineRoute
  ShellTableIndexRoute: typeof ShellTableIndexRoute
}

const ShellTableRouteRouteChildren: ShellTableRouteRouteChildren = {
  ShellTableFiletreeRoute: ShellTableFiletreeRoute,
  ShellTableGraphRoute: ShellTableGraphRoute,
  ShellTableMetadataRoute: ShellTableMetadataRoute,
  ShellTableTimelineRoute: ShellTableTimelineRoute,
  ShellTableIndexRoute: ShellTableIndexRoute,
}

const ShellTableRouteRouteWithChildren = ShellTableRouteRoute._addFileChildren(
  ShellTableRouteRouteChildren,
)

interface ShellRouteChildren {
  ShellTableRouteRoute: typeof ShellTableRouteRouteWithChildren
  ShellDocsRoute: typeof ShellDocsRoute
  ShellSnapshotsSelectionRoute: typeof ShellSnapshotsSelectionRoute
  ShellIndexRoute: typeof ShellIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellTableRouteRoute: ShellTableRouteRouteWithChildren,
  ShellDocsRoute: ShellDocsRoute,
  ShellSnapshotsSelectionRoute: ShellSnapshotsSelectionRoute,
  ShellIndexRoute: ShellIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
